name: Build ArchISO Stable
on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '0 0 */7 * *'
  
jobs:
  build:
    env:
      ATHENA_VERSION: 'rolling'
      ISO_VERSION: 'rolling' # It must be the same on profiledef.sh and installation_script
      ISO_ARCHITECTURE: 'x86_64'
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest
      options: --privileged 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Init Keys
        run: | 
          rm -rf /etc/pacman.d/gnupg
          pacman-key --init
          pacman-key --populate
          pacman -Syy

      - name: Install dependencies
        run: pacman -S --noconfirm archiso git github-cli openssh rsync sshpass wget tree
        
      - name: Build ArchISO
        run: |
          cd installation-scripts
          ./build.sh
      - name: Tree the Enviorment for Debugging Reasons
        run: | 
            tree $HOME | grep axyl
            tree $GITHUB_WORKSPACE | grep Axyl

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
            name: axyl-iso
            path: Axyl-Iso
            if-no-files-found: warn
            retention-days: 60
            compression-level: 0
            overwrite: false
