name: Build ArchISO Stable
on:
  # push:
  workflow_dispatch:
  #schedule:
     #- cron:  '0 0 */7 * *'
  
jobs:
  build:
    env:
      ATHENA_VERSION: 'rolling'
      ISO_VERSION: 'rolling' # It must be the same on profiledef.sh and installation_script
      ISO_ARCHITECTURE: 'x86_64'
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest
      options: --privileged 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Remove problematic mirrors
        run: |
          sed -i "/arch.mirror.constant.com/d" /etc/pacman.d/mirrorlist
          sed -i "/us.leaseweb.net/d" /etc/pacman.d/mirrorlist
          sed -i "/america.mirror.pkgbuild.com/d" /etc/pacman.d/mirrorlist
          sed -i "/geo.mirror.pkgbuild.com/d" /etc/pacman.d/mirrorlist
          sed -i "/london.mirror.pkgbuild.com/d" /etc/pacman.d/mirrorlist
          sed -i "/geo-mirror.chaotic.cx/d" /etc/pacman.d/chaotic-mirrorlist
          sed -i "/iad-us-mirror.silky.network/d" /etc/pacman.d/mirrorlist
          sed -i "/archlinux.uk.mirror.allworldit.com/d" /etc/pacman.d/mirrorlist
          sed -i "/mirror.lty.me/d" /etc/pacman.d/mirrorlist
          sed -i "/archlinux.mailtunnel.eu/d" /etc/pacman.d/mirrorlist
          sed -i "/pkg.fef.moe/d" /etc/pacman.d/mirrorlist
          sed -i "/mirror.cyberbits.eu/d" /etc/pacman.d/mirrorlist
          sed -i "/mirror.fra10.de.leaseweb.net/d" /etc/pacman.d/mirrorlist
          sed -i "/mirror.ubrco.de/d" /etc/pacman.d/mirrorlist
          sed -i "/europe.mirror.pkgbuild.com/d" /etc/pacman.d/mirrorlist
          sed -i "/mirror.sunred.org/d" /etc/pacman.d/mirrorlist
          sed -i "/mirror.netcologne.de/d" /etc/pacman.d/mirrorlist
          sed -i "/mirrors.eze.sysarmy.com/d" /etc/pacman.d/mirrorlist

      - name: Init Keys
        run: | 
          rm -rf /etc/pacman.d/gnupg
          pacman-key --init
          pacman-key --populate
          pacman -Syy

      - name: Install dependencies
        run: pacman -Syyu --noconfirm archiso git github-cli openssh rsync sshpass wget
        
      - name: Build ArchISO
        run: |
          cd installation-scripts
          ./build.sh
          
      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/axyl-os/axyl-iso
          cd axyl-iso
          for f in $(find $HOME/Axyl-Out -name '*.iso*'); do
            gh release upload v1-old $f --clobber
          done
          
