name: Build ArchISO Stable
on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '0 0 */7 * *'
  
jobs:
  build:
    env:
      ATHENA_VERSION: 'rolling'
      ISO_VERSION: 'rolling' # It must be the same on profiledef.sh and installation_script
      ISO_ARCHITECTURE: 'x86_64'
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest
      options: --privileged 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Init Keys
        run: | 
          rm -rf /etc/pacman.d/gnupg
          pacman-key --init
          pacman-key --populate
          pacman -Syy

      - name: Install dependencies
        run: pacman -S --noconfirm archiso git github-cli openssh rsync sshpass wget
        
      - name: Build ArchISO
        run: |
          cd installation-scripts
          ./build.sh
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
            name: axyl-iso
            path: $GITHUB_WORKSPACE/Axyl-Iso
            if-no-files-found: warn
            retention-days: 60
            compression-level: 0
            overwrite: false
          
      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/axyl-os/axyl-iso
          cd $GITHUB_WORKSPACE/Axyl-Iso
          for f in $(find $HOME/Axyl-Iso -name '*.iso*'); do
            gh release upload v23.11 $f --clobber
          done
