name: 'Close Stale Issues'

on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '0 0 */7 * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

inputs:
  repo-token: ${{ github.token }}
  stale-issue-message: 'closed automatically due to becoming stale, reopen to continue work'
  stale-pr-message: 'closed automatically due to becoming stale, reopen to continue work'
  close-issue-message: 'closed automatically due to becoming stale, reopen to continue work'
  close-pr-message: 'closed automatically due to becoming stale, reopen to continue work'
  days-before-stale: 8
  days-before-issue-stale: 8
  days-before-pr-stale: 8
  days-before-close: 6
  days-before-issue-close: 6
  days-before-pr-close: 6
  stale-issue-label: 'Stale'
  close-issue-label: 'Closed-Stale'
  exempt-issue-labels: 'enhancement'
  close-issue-reason: 'closed automatically due to becoming stale, reopen to continue work'
  stale-pr-label: 'Stale'
  close-pr-label: 'Stale-Closed'
 
runs:
  using: 'node20'
  main: 'dist/index.js'
